### ISSUE TITLE
QGIS crashes when trying to run SUEWS simple

### ISSUE THREAD

**Issue by marciaamatias** [UMEP-dev/UMEP#616]
Hello 

I've said here before I had this problem but I've encountered something that might be useful and that can help you help me, and others. 

So, when trying to run the SUEWs model, the SIMPLE version, having all the data, I've tried multiple times to run it and the model makes the QGIS crash. So, the programme completely shuts down. This happens on multiple computers, so the problem is coming from the plugin. 

I've tried running it and changing some of the components. **The model only Runs if we don't change the height of the meteorological forcing data. When we changed it, the model and QGIS shut down. So if we change the values from 49.600 to any other, it doesn't work.**

Obviously, my data was not collected at that height so the value is incorrect for the data I'm using. How can we overcome this? 

![Capturar](https://github.com/UMEP-dev/UMEP/assets/35871620/994d7613-424a-4e7f-a379-ae5ffb795e34)

**Comment by suegrimmond** [comment]
Are you using a comma - (rather than a dot) when you change the height?
Needs to be a dot.

**Comment by marciaamatias** [comment]
I'm using a dot. 

I've also tried to use an integer and the same happens 

Only works when I leave the 49.600

**Comment by biglimp** [comment]
I cannot replicate. I changed to 45.6 and could run without any error.
What version of QGIS and Python are you running? Go to Help>About. This is what I am using. Make sure that you are not running a session with Python 3.12 but 3.9. We are currently working on making UMEP running under 3.12. Can I also suggest that you download firstaid -plugin. Then we could more easily see what is causing the issues you have.

![image](https://github.com/UMEP-dev/UMEP/assets/11908356/6d89cc10-2934-4e9a-ae06-86f759c857b3)



On another note, I found another error when running the model multiple times in the same QGIS session where some files remains open and make the model crash. I will fix that. I will also fix the issue you found when changing file code. Both these issues will be reported in other issues by me.

**Comment by marciaamatias** [comment]
This is what I'm using and i'm running the model within the UMEP plugin, not on python 
![image](https://github.com/UMEP-dev/UMEP/assets/35871620/1b04aa9b-4af7-4c81-8aa2-27df12d14ac4)

Running with my data but not changing the value for the height it works. If I change it, it crashes 
![image](https://github.com/UMEP-dev/UMEP/assets/35871620/7ff5b461-4f0b-4282-8e72-7bb901b9438e)

On my python console
C:\Users\marci\AppData\Roaming\Python\Python39\site-packages\supy
-0.0009999999999998899
--- Logging error ---
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users/marci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\UMEP.py", line 445, in SUEWS_simple
    sg.run()
  File "C:\Users/marci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SuewsSimple\suews_simple.py", line 231, in run
    self.dlg.exec_()
  File "C:\Users/marci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SuewsSimple\suews_simple.py", line 606, in start_progress
    suews_wrapper.wrapper(self.model_dir, self.iface, year=YYYY)
  File "C:\Users/marci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\suewsmodel\suews_wrapper.py", line 59, in wrapper
    df_state_init = sp.init_supy(path_runcontrol)
  File "C:\Users\marci\AppData\Roaming\Python\Python39\site-packages\supy\_supy_module.py", line 103, in init_supy
    df_state_init = load_InitialCond_grid_df(
  File "C:\Users\marci\AppData\Roaming\Python\Python39\site-packages\supy\_load.py", line 1809, in load_InitialCond_grid_df
    logger_supy.info("All cache cleared.")
Message: 'All cache cleared.'
Arguments: ()

**Comment by biglimp** [comment]
Then it must be something with your met forcing data. What if you first press "Add settings from test data" and then change forcing height? Then you will use a full year of data from and settings from London. Running the model for only one day as you do is not recommended.

**Comment by biglimp** [comment]
Did you have the same issue with testdata? Can I close this?

**Comment by marciaamatias** [comment]
yes, the same happened. but you can close this.
